### ISSUE TITLE
collapse_isoforms_by_sam.py give both strand for one gene

### ISSUE THREAD

**Issue by pengchy** [PacificBiosciences/cDNA_primer#13]
Hi all,

I have used collapse_isoforms_by_sam.py to reduce the redundancy from the gmap produced sam file. One question occurred that for one gene locus on the reference sequence, many transcripts were clustered into two genes. These two gene locate on different strand of the reference, but their exons were almost the same to each other, and obviously the same gene. I compared the sam file and found the flag always 0 or 16. It seems that their is not strand information in the sam file.

The question is how collapse_isoforms_by_sam.py judge the strand information from the sam and how to resolve give the correct strand information.

Thank you and appreciate for any suggestions

Best,
Pengcheng Yang

**Comment by Magdoll** [comment]
Hi,

Currently the GMAP reader that ToFu uses parses the "XS:A:" tag to get strand information. In cases where the "XS:A:?" tag is given (so strand is uncertain), it falls back to using looking at the flag field. 

One of the things I believe should probably be done, is, given that the Iso-Seq output is already strand oriented, GMAP should probably really be run with sense strand only. This is the "-z" option in GMAP. 

-z, --direction=STRING         cDNA direction (sense_force, antisense_force,
                                   sense_filter, antisense_filter,or auto (default))

This is likely to be especially useful in cases for single-exon transcripts, since GMAP often outputs an unknown strand (since there are no canonical junctions from which to determine best strand and it does not know that Iso-Seq output is already stranded).

Thus, I recommend trying to run GMAP using:

"gmap -z sense_force ....." and follow up with collapse script.

I will consider adding this behavior in tofu_wrap.py which calls gmap as part of the process.

Thanks,
--Liz

**Comment by Magdoll** [comment]
Hi,

The new version of tofu_wrap.py (as of version 2.2.1) now uses strand enforcement through "gmap -z sense_force."

Closing bug.
