### ISSUE TITLE
what sampling depth or How many SMRT cells should I use?

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#16]
I want to do the RNA sequencing using pacbio SMRT, I have got the transcriptome information, but I don't know how many cells should I use ? And what the sampling depth is enough?

Thanks a lot for anly replyO(∩_∩)O

**Comment by Magdoll** [comment]
Hi,
There is no fixed answer for this question as it depends on a lot of factors. It is also a question that is more related to experimental design and not directly related to the GItHub ToFU code.

I recommend first talking to your local PacBio FAS for experimental design guidance. Depending on your needs, the FAS can help you draw up the necessary sequencing depth.

Thanks,
--Liz

**Comment by 52teth** [comment]
@Magdoll  Thanks a lot. I just want to have a general idea about my experiment. Because I have  nothing about the experimentO(∩_∩)O~

**Comment by Magdoll** [comment]
Hi,
If you already have data, what ppl do in the past in run rarefaction curves. There is a lot of simplification in drawing the curves but it gives you some sense of saturation. You can take a look at this [wiki](https://github.com/PacificBiosciences/cDNA_primer/wiki/Bioinfx-study:-Sampling-depth%3F-Simulated-rarefaction-curves-based-on-real-data) for some reference.

If you do not know the transcriptome complexity of your sample, then I think you should just make a target of "want to sequence X sequences" (note I say sequences, not transcripts, since you don't know the complexity). That is pretty easy to convert into SMRTcells because # of sequences is solely determined by loading concentration and not related to sample complexity.
