### ISSUE TITLE
Why does the collapse work run after the filter work?

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#27]
I have cheked the Collapsing redundant transcripts by collapse_isoforms_by_sam.py. I find that the collapse work (b.process_records()) run after the filter job(b.iter_gmap_sam(),which filtering out min_aln_coverage and min_aln_identity), I want to see wheather the low aln_identity and low aln_coverage is belong to any group that with high_identity and high_coverage, so does it matter when I do the collapse work before gmap filtering? 

group like this: 
seq1 ************xx****xx   low identity|low coverage 
seq 2 ************                high identity|high coverage
** reprensents good algnment nt;
*x reprensents bad algnment nt;
if filtering first, then the seq1 is filtered. But the seq2 may be not a full length while the seq1 may be a new transcript.

**Comment by Magdoll** [comment]
The current design is that we filter out "bad" alignments (low identity or coverage) because lower quality means it's harder to determine whether they represent true alternative / novel splice forms or are just junk.

One way you can figure out the bad / good relationship is run collapse script twice. Once with the default coverage/identity threshold, once with lower threshold. Then look at the .group.txt files from the two output. That should give you some idea of which of the low quality ones can fit in with the high quality ones.

--Liz

**Comment by 52teth** [comment]
@Magdoll Thanks a lot for you reply.
If I think my sequence is reliably, I do the collapse and the low identity and coverage is due to the alignment problem. So I can wonder the the genome is not perfect or just the specific sequence strcture of the sample.  So I  think the low identity or coverage alignment may be usefull for discovering new isform. I 'll have a try.
