### ISSUE TITLE
TOFU pileline：get abundance independently

### ISSUE THREAD

**Issue by Dongxn** [PacificBiosciences/cDNA_primer#48]
Hi,
for some resons, I've run [combine_quiver_results.py=>gmap=>collapse_isoforms_by_sam.py] independently but not just using tofu_wray,py, and got outputs like:
###############################
$ ll combined/
all_sizes.fasta
all_sizes.fasta.sam
all_sizes.fasta.sorted.sam
all_sizes.fastq
all_sizes.sorted.5merge.collapsed.gff
all_sizes.sorted.5merge.collapsed.gff.unfuzzy
all_sizes.sorted.5merge.collapsed.group.txt
all_sizes.sorted.5merge.collapsed.group.txt.unfuzzy
all_sizes.sorted.5merge.collapsed.rep.fa
all_sizes.sorted.5merge.ignored_ids.fa
all_sizes.sorted.5merge.ignored_ids.txt
all_sizes.sorted.5merge.log
all_sizes.quivered_hq.fastq
all_sizes.quivered_lq.fastq
combined.hq_lq_pre_dict.pickle
################################
(1)I am wondering if I could get "abundance.txt and read_stat.txt" based on the above outputs ? 
(2)And for a no-reference study, I got some outpus after running [combine_quiver_results.py=>cd-hit], if these files could generate  "abundance.txt and read_stat.txt" ?
############################
cd_hit_collapsed.fa
cd_hit_collapsed.fa.clstr
all_sizes.quivered_hq.fastq
all_sizes.quivered_lq.fastq
combined.hq_lq_pre_dict.pickle
############################

Thank you for your kind reply :)

**Comment by Magdoll** [comment]
Hi,

(1) Yes, for a (genome) collapsed output you can generate the counts (read_stat and abundance.txt) using an additional script. Download: https://github.com/Magdoll/ICE/blob/master/run_just_collapse_and_later.py_log to the same directory.

You will probably need to make a few name changes.

ex: 

change `all_sizes.quivered_hq.fastq` to `all_sizes.fastq` (or whichever is the fastq you actually used to get the GMAP SAM file)

change `/home/UNIXHOME/etseng/share/gmap_db_new/' to properly reflect your GMAP db location (is the `-D` option in gmap) and `SIRV` to the GMAP name (is the `-d` option in GMAP). The script will automatically detect, however, that the SAM file already existed and will not re-run GMAP again unless you delete the SAM file first. But I like to change it just in case you are using the script in the future :)

If you used only HQ, then the rest of the script should work.

If you used both HQ+LQ, you may have the change the following line from:
```
tofu_wrap.get_abundance(hq, a['HQ'], hq)
```

to
```
b = a['HQ']
b.update(a['LQ'])
tofu_wrap.get_abundance(hq, b, hq)
```

Otherwise the script will probably complain it doesn't understand the LQ sequence IDs.

You also probably need to run this interactively (depending on where you install and call tofu_wrap), like using ipython or python interpreter and simply copy-pasting the script. Let me know if you encounter issues with running this. If you do run into issues, please copy the error message and give me a few lines from your SAM file because it's probably breaking from the sequence IDs differences.

(2) Good request. I have not supported using CD-HIT yet! Can you give me your CD-HIT parameters? I can run a test on my end and try to support it. I just need to know the CD-HIT format output you get. I will need the CD-HIT version + your CD-HIT parameters. I will file this as an issue and work on it (may not be as soon but I will get to it).

**Comment by Dongxn** [comment]
thank you Magdoll,
(1) I've try the srcipt but it seems it will rerun gmap while all_sizes.fasta and all_sizes.fasta.sam exist,

**$ python /SMRT/python_virtualenv/bin/run_just_collapse_and_later.py**
CMD: gmap -D /home/Tetur_gmap/ -d Tetur_gmap -n 0 -t 24 -z sense_force --cross-species -f samse all_sizes.fasta > all_sizes.fasta.sam 2> all_sizes.fasta.sam.log
[running+]
**what I have in the directory:**
all_sizes.fasta
all_sizes.fasta.sam
all_sizes.fasta.sorted.sam
all_sizes.fastq
all_sizes.sorted.5merge.collapsed.gff
all_sizes.sorted.5merge.collapsed.gff.unfuzzy
all_sizes.sorted.5merge.collapsed.group.txt
all_sizes.sorted.5merge.collapsed.group.txt.unfuzzy
all_sizes.sorted.5merge.collapsed.rep.fa
all_sizes.sorted.5merge.ignored_ids.fa
all_sizes.sorted.5merge.ignored_ids.txt
all_sizes.sorted.5merge.log
all_sizes.quivered_hq.fastq
all_sizes.quivered_lq.fastq
combined.hq_lq_pre_dict.pickle

**$cat run_just_collapse_and_later.py**
# IPython log file

from cPickle import *
a=load(open('combined.hq_lq_pre_dict.pickle'))
import tofu_wrap
hq = tofu_wrap.run_collapse_sam('all_sizes.fasta', '/home/Tetur_gmap/', 'Tetur_gmap')
b = a['HQ']
b.update(a['LQ'])
tofu_wrap.get_abundance(hq, b, hq)
tofu_wrap.run_filtering_by_count(hq, hq+'.min_fl_2', min_count=2)

(2)
version: 4.6.1
**$cd-hit-est -i all_sizes.quivered_hq.fasta -c 0.99 -T 6 -G 0 -aL 0.90 -AL 100 -aS 0.99 -AS 30 -o cd_hit_collapsed.fa**
**$less cd_hit_collapsed.fa**
>i0HQ_T01|c73/f38p10/1727 isoform=c73;full_length_coverage=38;non_full_length_coverage=10;isoform_length=1727
ATAATTAACTTTGCTTTTGCTAGTTCAATAGTTTACCTTCATAGGAATATCTTTGCAAACTCAAAGTTAAAAAGTTCTAATAAATTCATCTGAAAATGAGGATCTTCGTTGTAACTTGTGTTCTTTCCTGCGCCTTCATGGCATCCGCTTCACCCCTTTTATGCGGTGGTGGAT.......

**Comment by Magdoll** [comment]
Hi,
(1) Ah, indeed, you probably have an earlier version of `tofu_wrap.py` that doesn't check the SAM file already existed. The version you have is probably the [master version](https://github.com/PacificBiosciences/cDNA_primer/blob/master/pbtranscript-tofu/pbtranscript/pbtools/pbtranscript/tofu_wrap.py). A simple fix (if you are willing to quickly modify the code and re-compile/install ToFU in the VENV) is to add a line to `tofu_wrap.py`.

Change line 161 in `tofu_wrap.py` from:

```
cmd = "gmap -D {d} -d {name} -n 0 -t {cpus} -z sense_force --cross-species -f samse {fq} > {fq}.sam 2> {fq}.sam.log".format(\
            d=gmap_db_dir, name=gmap_db_name, cpus=cpus, fq=fastq_filename)
```

To:

```
   if not os.path.exists(fastq_filename + '.sam'):
        cmd = "gmap -D {d} -d {name} -n 0 -t {cpus} -z sense_force --cross-species -f samse {fq} > {fq}.sam 2> {fq}.sam.log".format(\
                d=gmap_db_dir, name=gmap_db_name, cpus=cpus, fq=fastq_filename)
        print >> sys.stderr, "CMD:", cmd
        subprocess.check_call(cmd, shell=True)
```

And that would check the SAM file exists. 

Still, re-running GMAP isn't wrong, just wasting time you already spent. Let me know if you encounter issues with the rest of the code. 


(2) Thanks. I've opened a [new issue](https://github.com/PacificBiosciences/cDNA_primer/issues/49) for this. I will notify you when I have a solution.

**Comment by Dongxn** [comment]
thank you Magdoll, I will try that

**Comment by Dongxn** [comment]
Hi, I've tried the script and it works!  thank you :)
Then I tried to run just "tofu_wrap.get_abundance(hq, b, hq)" since the sricpt could not modify parameters of "run_collapse_sam"(min coverage, min identity etc), so I write a new script based on the older one:

`# IPython log file
from cPickle import *
a=load(open('combined.hq_lq_pre_dict.pickle'))
import tofu_wrap
hq=load(open('all_sizes.fasta.5merge.*'))
b = a['HQ']
b.update(a['LQ'])
tofu_wrap.get_abundance(hq, b, hq)`

and came to some error, I am not sure if it works.

**Comment by Magdoll** [comment]
Hi,

Actually you *can* change the min identity and min coverage.

The full set of parameters is:

tofu_wrap.run_collapse_sam(fastq_filename, gmap_db_dir, gmap_db_name, cpus=24, min_coverage=0.99, min_identity=0.95, dun_merge_5_shorter=False, max_fuzzy_junction=5)

In other words, you can change the original script to use any of these parameters. Just change:

```
hq = tofu_wrap.run_collapse_sam('all_sizes.quivered_hq.fastq', '/home/UNIXHOME/etseng/share/gmap_db_new/', 'SIRV')
```

to

```
hq = tofu_wrap.run_collapse_sam('all_sizes.quivered_hq.fastq', '/home/UNIXHOME/etseng/share/gmap_db_new/', 'SIRV', min_coverage=XXX, min_identity=YYY)
```

**Comment by Dongxn** [comment]
thank you! Magdoll  :)
