### ISSUE TITLE
How to get aubudance .txt file from RS_IsoSeq pipeline results?

### ISSUE THREAD

**Issue by yang91** [PacificBiosciences/cDNA_primer#51]
Hello,
  I've ran the  RS_IsoSeq and collapse and remove redundant transcripts for every cell seperately.  But this way couldn't produce collapsed.abundance.txt, which is necessary for later chaining transcripts' id. I've already read the issue#48 "TOFU pileline：get abundance independently" and tried the script 'run_just_collapse_and_later.py' , but there are no combined.hq_lq_pre_dict.pickle file in my outputs, so it didn't work. Is there any other way to get the abundance .txt ?

**Comment by Magdoll** [comment]
Hi,
Because you ran from RS_IsoSeq (official pipeline) instead of ToFU, you don't quite have all the files in place to run the collapse script but this can be manually modified to work.

Here are the steps:

1. Locate the HQ isoform sequence from RS_IsoSeq output. Most likely it will be in a place like `/pbi/analysis/smrtportal/beta/userdata/jobs/095/095694/data/polished_high_qv_consensus_isoforms.fastq`.

2. Create a clean directory and copy the HQ isoform fastq file over. We need to copy it because we are making changes to the sequence header to be compatible with ToFU scripts.

```
cp polished_high_qv_consensus_isoforms.fastq all_sizes.quivered_hq.fastq
sed -i s'/^@c/@i0HQ_sample1|c/g' all_sizes.quivered_hq.fastq
```

This changes the sequence IDs from 
`c18/f13p133/887 isoform=c18;full_length_coverage=13;non_full_length_coverage=133;isoform_length=887`
to
`@i0HQ_sample1|c18/f13p133/887 isoform=c18;full_length_coverage=13;non_full_length_coverage=133;isoform_length=887`

3. Modify `just_run_tofu_from_collapse.py_log` to not needing the pickle. Instead we will directory provide the information necessary.

```
import tofu_wrap
hq = tofu_wrap.run_collapse_sam('all_sizes.quivered_hq.fastq', '/home/UNIXHOME/etseng/share/gmap_db_new/', 'hg38', max_fuzzy_junction=5, dun_merge_5_shorter=True)
from cPickle import *

#a=load(open('combined.hq_lq_pre_dict.pickle'))  ## this line is commented out

a = {}
a['HQ'] = {'i0HQ_sample1': '/pbi/analysis/smrtportal/beta/userdata/jobs/095/095694/data/clusterOutDir/'}

tofu_wrap.get_abundance(hq, a['HQ'], hq)
tofu_wrap.run_filtering_by_count(hq, hq+'.min_fl_2', min_count=2)
tofu_wrap.run_filtering_away_subsets(hq+'.min_fl_2', hq+'.min_fl_2.filtered', fuzzy_junction=5)
```

All we are doing here is letting the script know that sequences with the prefix `i0HQ_sample1` comes from the Iso-Seq run that is from `/pbi/analysis/smrtportal/beta/userdata/jobs/095/095694/data/clusterOutDir/`. You should be able to get .abundance.txt now.

Let me know if you encounter any issues.

**Comment by yang91** [comment]
Thanks for your patient reply! I've tried and it went well, except a little trouble. When I run just_run_tofu_from_collapse.py, it will rerun GMAP even bam files exist. Follow the issue#48 solution, I tried to change my tofu_wrap.py, while things went different. I only have very few lines in my tofu_wrap.py, showed as below;

#!/home/smrtanalysis/tofu/bin/python
# EASY-INSTALL-SCRIPT: 'pbtools.pbtranscript==2.2.3','tofu_wrap.py'
__requires__ = 'pbtools.pbtranscript==2.2.3'
__import__('pkg_resources').run_script('pbtools.pbtranscript==2.2.3', 'tofu_wrap.py')
~

I think this may due to my installion order, because I firstly installed smrtanalysis software, then installed pbtranscrpt-tofu as the guides in tofu's step-by-step installation. How could I solve this?

**Comment by Magdoll** [comment]
Hi,

Re-running GMAP is not an issue per se, as I mentioned in issue #48 . 
What exactly is the problem are you encountering?

--Liz

**Comment by yang91** [comment]
Actually I want enable the tofu_wrap.py to check existed SAM files, while my tofu_wrap.py script is not same as given in issue #48 master version. But now I have another problem, the **just_run_tofu_from_collapse.py produce this error and exited**:

Traceback (most recent call last):
  File "/home/smrtanalysis/tofu/bin/just_run_tofu_from_collapse.I01.1-2K.A01.py", line 13, in <module>
    tofu_wrap.run_filtering_away_subsets(hq+'.min_fl_2', hq+'.min_fl_2.filtered', fuzzy_junction=5)
AttributeError: 'module' object has no attribute 'run_filtering_away_subsets'

**Here is my just_run_tofu_from_collapse.py:**

import tofu_wrap
hq = tofu_wrap.run_collapse_sam('all_sizes.quivered_hq.fastq','/opt/smrtanalysis/analysis/bin/gmap_home/share/hg38', 'hg38', max_fuzzy_junction=5, dun_merge_5_shorter=True)

from cPickle import *

#a=load(open('combined.hq_lq_pre_dict.pickle'))  ## this line is commented out

a = {}
a['HQ'] = {'i0HQ_sample1': '/home/smrtanalysis/userdata/jobs/016/016482/data/clusterOutDir/'}

tofu_wrap.get_abundance(hq, a['HQ'], hq)
tofu_wrap.run_filtering_by_count(hq, hq+'.min_fl_2', min_count=2)
tofu_wrap.run_filtering_away_subsets(hq+'.min_fl_2', hq+'.min_fl_2.filtered', fuzzy_junction=5)

I felt confused about this, because everything seems normal and I also got the **output in my dir** (showed as below)
all_sizes.quivered_hq.fastq
all_sizes.quivered_hq.fastq.no5merge.collapsed.abundance.txt
all_sizes.quivered_hq.fastq.no5merge.collapsed.gff
all_sizes.quivered_hq.fastq.no5merge.collapsed.gff.unfuzzy
all_sizes.quivered_hq.fastq.no5merge.collapsed.group.txt
all_sizes.quivered_hq.fastq.no5merge.collapsed.group.txt.unfuzzy
all_sizes.quivered_hq.fastq.no5merge.collapsed.min_fl_2.abundance.txt
all_sizes.quivered_hq.fastq.no5merge.collapsed.min_fl_2.gff
all_sizes.quivered_hq.fastq.no5merge.collapsed.min_fl_2.rep.fq
all_sizes.quivered_hq.fastq.no5merge.collapsed.read_stat.txt
all_sizes.quivered_hq.fastq.no5merge.collapsed.rep.fq
all_sizes.quivered_hq.fastq.no5merge.ignored_ids.txt
all_sizes.quivered_hq.fastq.sam
all_sizes.quivered_hq.fastq.sam.log
all_sizes.quivered_hq.fastq.sorted.sam

What happened?

**Comment by Magdoll** [comment]
The error message you get is:
```
Traceback (most recent call last):
File "/home/smrtanalysis/tofu/bin/just_run_tofu_from_collapse.I01.1-2K.A01.py", line 13, in 
tofu_wrap.run_filtering_away_subsets(hq+'.min_fl_2', hq+'.min_fl_2.filtered', fuzzy_junction=5)
AttributeError: 'module' object has no attribute 'run_filtering_away_subsets'
```

Which is exactly what it says. Your `tofu_wrap.py` is missing a function called `run_filtering_away_subsets`. 

You indicated that your `tofu_wrap.py` is difference from issue #48. My guess is you have an older version of tofu_wrap.py and that older version does not have the new function I added called `run_filtering_away_subsets`.

Since `run_filtering_away_subsets` is the last step in the script, you were able to execute all the other steps up until the last step.

If you had succeeded running all including the last filter step, you should've seen the output called:

`all_sizes.quivered_hq.fastq.no5merge.collapsed.min_fl_2.filtered.abundance.txt`
`all_sizes.quivered_hq.fastq.no5merge.collapsed.min_fl_2.filtered.gff`
etc

So, please update your `tofu_wrap.py`. Most likely you can directly download the `tofu_wrap.py` version in the prebam branch (see issue #48). Directly copy it over your existing `tofu_wrap.py`, re-compile and re-install in your ToFU virtual environment, and now it shold work.

**Comment by yang91** [comment]
Hi @Magdoll
Thank you for your advice! One more question, what exactly dd the run_filtering_away_subsets do?  I'm not very familiar with the tofu functions.

**Comment by Magdoll** [comment]
@yang91 

The script filter_way_subsets removes potentially degraded isoforms that are shorter than another longer isoform.

Ex:

IsoformA is exon 1, 2, 3, 5
IsoformB is exon 2, 3, 5
IsoformC is exon 2, 3

In this case, IsoformB is a potentially degraded product of IsoformA. But IsoformC is not, because it has a different 3' end (Iso-Seq respects 3' ends because of polyA tail signal). So after you run filter away subset, only IsoformA and IsoformC will remain.

--Liz

**Comment by yang91** [comment]
Sorry for my so late reply.........
You gave the advice that I should downloaded the prebam branch tofu_wrap.py, but I just found this https://github.com/PacificBiosciences/cDNA_primer/blob/master/pbtranscript-tofu/pbtranscript/pbtools/pbtranscript/tofu_wrap.py, which seems like the "master version" you said in #48 , and I couldn't find any information about prebam branch in #48 . It really confused me. So could you please infer me a link?

**Comment by Magdoll** [comment]
hi @yang91 , looks like mis-quote the issue. It should be #53 that has the instructions to prebam branch.

**Comment by yang91** [comment]
Hi @Magdoll , I've found the prebam branch as your guide, but something went wrong during installation. I've build a new virtual env and install the realiable python packages just like the wiki script says. While 'git clone https://github.com/PacificBiosciences/cDNA_primer/tree/prebam' didn't work, I downloaded it from github directly. Then I ran the latter step and got "AttributeError: Extension instance has no attribute '_convert_pyx_sources_to_lang'" at the make step. I've tried solutions in #17 while it didn't work, Did the prebam branch have special installation requirements?

**Comment by Magdoll** [comment]
Which solutions did you try in #17? all of them?

I think another possibility is disutil issues. Can you use the "master" branch setup.py from below:

https://github.com/PacificBiosciences/cDNA_primer/blob/master/pbtranscript-tofu/pbtranscript/setup.py

replace the prebam setup.py with this one and re-compile. 

Let me know how it goes.

--Liz

**Comment by yang91** [comment]
Yes, I've tried all solutions in #17. I just tried replace the setup.py file and re-compile, but it reported something like "Not found ../../third-party" and got stuck. While I've used a slightly different way from wiki guides and I succeed. 
Since I've had all other packages installed but bx-python in my new virtual env, and there seems like python version like 2.7 could work, so I guessed the problem may caused by upgrade and tried not to upgrade pip and setuptools, and it succeed. Really a good luck.
PS: I also installed 'urllib3' and 'hmac' packages through pip. Hope for help.

Lastly, thank you so much for your warm-hearted and helpful reply, @Magdoll !
