### ISSUE TITLE
tofu_wrap.py error in single server

### ISSUE THREAD

**Issue by wangxinbio** [PacificBiosciences/cDNA_primer#53]
when I use tofu_wrap.py on my server (Non cluster), the tofu_wrap will give a error "/data/pacbio/wrap_test/tofu_wrap/3to4kb_part0/tofu_wrap/4to5kb_part0/isoseq_flnc.fasta". It should run in the 
"/data/pacbio/wrap_test/tofu_wrap/4to5kb_part0/isoseq_flnc.fasta". However, The document was false. Wheather this script only run in cluster and not on the single server ?
The comment : 
tofu_wrap.py --bas_fofn input.fofn --ccs_fofn reads_of_insert.fofn -d tofu_wrap --quiver --quiver_nproc 63 --gcon_nproc 63 --blasr_nproc 63 --report isoseq_cluster_info.csv  --summary cluster_summary.txt --gmap_db genome --gmap_name potato --output_seqid_prefix 2_3k --nfl_fa isoseq_nfl.fasta isoseq_flnc.fasta consensus.fasta

**Comment by Magdoll** [comment]
Hi,
I need some more information to debug this.

What is the full error message from tofu_wrap.py? Please paste it here.

Is it saying something like "CANNOT FIND FILE CALLED `/data/pacbio/wrap_test/tofu_wrap/3to4kb_part0/tofu_wrap/4to5kb_part0/isoseq_flnc.fasta`"??

And when this happens, have you tried directly re-running `tofu_wrap.py` again from the same location. If I'm guessing correctly, this sometimes comes from some very strange Python path behavior (that we have not been able to track down). When it happens, `tofu_wrap.py` dies, BUT since you already have the existing size bins run (0-1, 1-2, 2-3, 3-4 already completed), if you directly restart tofu_wrap.py, it should work.

So:
(1) please do an `ls` of the following and paste the result back
```
ls /data/pacbio/wrap_test/tofu_wrap/isoseq_flnc.fasta
ls /data/pacbio/wrap_test/tofu_wrap/all*fasta
```

(2) please report the full error message
(3) please try re-running tofu_wrap.py directly again and let me know if the same error message happens.

--Liz

**Comment by wangxinbio** [comment]
Thank you. I re-runned the tofu_wrap.py. I seems Ok in this step. But a new error happened in 11to12k. It showed like this " *** Error in `daligner': malloc(): memory corruption: 0x0000000001953d00 ***
*** Error in `daligner': malloc(): memory corruption: 0x0000000001953d00 ***". How to resolve it? Thank you.

**Comment by Magdoll** [comment]
@wangxinbio if you have a later version of ToFU, this error should be OK. Is the job still running? If it is, no need to worry about it.

--Liz

**Comment by wangxinbio** [comment]
Thank you. Where can I download the later version?

**Comment by Magdoll** [comment]
Hi @wangxinbio did the process die already? If it did, it is probably an earlier version. The latest version is in the "prebam" branch. There are minor differences in the input (mainly, instead of FASTA, you now provide a FASTQ file, but everything else is the same).  I no longer update the "master" branch because I'm about to move to ToFU2 (which is not backwards-compatible).

To use "prebam", download / git pull it from: 
https://github.com/PacificBiosciences/cDNA_primer/tree/prebam

(make sure it's the "prebam" branch, not the "master" branch)

Install are you previously did under a virtual environment. I might recommend creating a new venv and keeping the old one just in case you have trouble with the new one.

Once completed, the syntax for `tofu_wrap.py` is:

```
tofu_wrap.py --nfl_fa isoseq_nfl.fastq  --bas_fofn input.fofn [--fasta_fofn input.fasta.fofn] -d clusterOut --use_sge --max_sge_jobs 40 --blasr_nproc 20 --gcon_nproc 8 --quiver_nproc 8 --quiver --bin_manual "(0,1,2,3,8)"[ --output_seqid_prefix sample507] [--sge_queue def66] isoseq_flnc.fastq final.consensus.fasta
```

So the only difference is, instead of `isoseq_flnc.fasta`', you give it a FASTQ file `isoseq_flnc.fastq` and instead of `isoseq_nfl.fasta` you give it `isoseq_nfl.fastq`.  YOu also no longer need to supply `--ccs_fofn reads_of_insert.fofn` (it will simply be ignored).

Parameters marked in [ ] are optional. Since you already previously ran `tofu_wrap.py`, you should have `input.fasta.fofn` already created. It is likely in `clusterOut/fasta_fofn_files/input.fasta.fofn`. Simply copy it over and use it. Let me know if you run into any problems.

--Liz

**Comment by wangxinbio** [comment]
Ok. I always use the tofu-2.2.3. When I search the 2.2.2, I always considered it a order version. I will try it on my server. Thank you very much.
