### ISSUE TITLE
qv_prob_threshold

### ISSUE THREAD

**Issue by danielrhyduke** [PacificBiosciences/cDNA_primer#66]
I was wondering if there's a reason for changing the qv_prob_threshold from 0.1 to 0.03?  Also, are there any documents explaining how this parameter relates to blasr?

https://github.com/PacificBiosciences/cDNA_primer/blob/17c3d4628248365127e8cac3e3afd649f8e8954f/pbtranscript-tofu/pbtranscript/pbtools/pbtranscript/ice/IceIterative.py#L47

https://github.com/PacificBiosciences/cDNA_primer/commit/d27bfc75b7fe476dc3d6fff006284b953c1fce4e

**Comment by ylipacbio** [comment]
This qv threshold is not used by BLASR, it is a (empirical) threshold indicating whether or not an insertion/deletion/substitution event in a position is expected.

**Comment by danielrhyduke** [comment]
Yes, it's not used by blasr but it looks like it's used as as threshold in eval_blasr_alignment that can  affect whether isoforms are binned to the HQ quiver file or the low quality file.
https://github.com/PacificBiosciences/cDNA_primer/search?utf8=%E2%9C%93&q=qv_prob_threshold

For our data, in the smrt portal 2.3 the value's set to 0.1 and the IsoSeq protocol results in many more isoforms being tagged as HQ than in the current pbtranscript built using pitchfork or directly from the tofu repo with a threshold of 0.03.

If there's more detailed information on this and other parameters, a link would be appreciated.

**Comment by ylipacbio** [comment]
Yes, this qv threshold is used to evaluate alignments.

function eval_blasr_alignment evaluates how good an alignment (created by BLASR) is looking at the QV values. For example, if an blasr alignment has an insertion at a position, while insertion QV of that position obtained from the raw read or ccs read is greater than the qv threshold, then score of this alignment is increased.

You are observing more HQ isoforms in SA2.3 workflows, probably not because of changes to this qv threshold. It's like due to the fact that criteria for HQ isoforms is more stringent now requiring at least two full-length non-chimeric reads to support an isoform to call it HQ other than 1.

**Comment by danielrhyduke** [comment]
Thanks for the details.

Given that I've run the same sample (same size fraction) on multiple SMRT cells, is it possible to combine all the isoseq_flnc.fasta files to possibly 'rescue' isoforms that only have one full-length non-chimeric read per cell?

If yes, is there documentation on how to do so? Or, should I just:
 1. concatenate the isoseq_flnc.fasta files
 2. concatenate the isoseq_nfl.fasta files
and, 3. create unions of the ccs_fofn and bas_fofn files
before running pbtranscript cluster?

**Comment by ylipacbio** [comment]
Yes, you can combine all isoseq_flnc.fasta and isoseq_nfl.fasta to rescue isoforms with one FLNC read.

For combined datasets, TOFU or the latest SmrtAnalysis build will be much faster and is recommended.
