### ISSUE TITLE
determining the accuracy of high quality and low quality isoforms

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/cDNA_primer#67]
To whom it may concern,

We have successfully followed the isoseq protocol and the pipeline to obtain high quality and low quality transcripts for gene annotation. We observed significant number of low quality transcripts from the >5kb library than the 1-2kb library. This is probably because there is significantly low number of full length and non-full length transcripts for the >5kb library compared to the 1-2kb library.

It is recommended in the wiki to use the low quality transcripts with caution. We wanted to select the low quality transcripts for gene annotation based on the number of full passes, number of full-length transcripts, non of non-full length transcripts and sequence accuracy. 

We were not able to find any log for the sequence accuracy for post quiver and I am aware that the high quality and low quality transcripts are divided based on the accuracy (>99%).  We would like to know if we can calculate the sequence accuracy as the same way the pipeline does.

Best,
Jin

**Comment by ylipacbio** [comment]
The QVs of LQ isoforms are available in the job dir.

If you are using SMRTAnalysis 3.0+, you will be able to find QVs of LQ isoforms in 
{job_dir}/tasks/pbtranscript.tasks.separate_flnc-0/combined/all.polished_lq.fastq

**Comment by sjin09** [comment]
I am using SMRTanalsys2.3.0. In this version, the tasks directory is missing. The directories that I can see are log, output, quivered, scripts and tmp. Would any of these directories have the relevant information?

Thank you for the swift reply!

**Comment by ylipacbio** [comment]
For 2.3.0, you can find FASTQ of LQ isoforms at


data/polished_low_qv_consensus_isoforms.fastq

________________________________

**Comment by Magdoll** [comment]
To elaborate @ylipacbio's point, in SMRTANalysis 2.3 you will have to calculate the accuracy from the FASTQ phred scores yourself since we didn't print it out. Below is a Python code that helps you do so:

You will need to be under the SMRTAnalysis environment to have access to the library `pbcore.io`. Otherwise you can also use other generic fastq readers like from BioPython.

By default, the first 100 bp (5' end) and last 30 bp (3' end) are not included as part of the accuracy calculation since they tend to have much less coverage and have very low phred scores. We find that excluding them tend to have little effect downstream and it's better to only look at the accuracy in the middle of the sequences.  You can certainly change the parameters as you like.

```
from pbcore.io.FastqIO import FastqReader

input = 'all_quivered_lq.fastq'
trim5 = 100  # ignore the first 100 bp
trim3 = 30   # ignore the last 30 bp

for r in FastqReader(input):
    num_err = sum(10**(-int(x)/10.) for x in r.quality[trim5:-trim3])
    acc = 1 - num_err*1./(len(r.sequence)-trim5-trim3)
    print r.id, acc
```

**Comment by sjin09** [comment]
Thank you @Magdoll! That was the answer I required. 

I wanted to ask one more question. In many of the low quality transcript cases, the quality score is a stretch of !, which is 0. The accuracy is also calculated to be zero using your script.

I have often found for example, a full-length transcript that has been read multiple times by the polymerase to form a consensus sequence (full-length-transcript number=1, number of full_passes > 2).

The average accuracy of the PacBio sequence should be 85% and I assume that with the circularconsensus module, the average accuracy should have increased above 85%. I do not understand why 0 is calculated as the accuracy for some of these transcripts. 

Thank you so much for all the help!

**Comment by sjin09** [comment]
I was also able to observe some transcripts with full_length_coverage=1,non_full_length_coverage=0,number_of_full_passes as 0. However, the sequence accuracy was determined to be 98% using the script you have provided above. 

I was wondering how this is possible? I have attached the transcript with such case. 

[c39928.txt](https://github.com/PacificBiosciences/cDNA_primer/files/779104/c39928.txt)

**Comment by Magdoll** [comment]
@nlhepler will be able to answer more detailedly about the 0 phred score in the consensus. But basically these lower case bases actually have no consensus called, either due to filtering, lack of coverage (most likely the explanation since it's at the ends), or lack of convergence in the consensus model. This is also why in determining HQ vs LQ for post-Quiver/Arrow sequences, Iso-Seq does not use these ends as the QVs here tend to be uninformative.

The c39928 example -- it looks like this is probably from an older version of Iso-Seq (because I know more recent Iso-Seq HQ criterion requires at least 2 FL reads. 1FL reads being in HQ is an older version), and our exact parameters for trimming (100 bp on 5' and 30 bp on 3') plus how we make the HQ cutoff (default 99%) have changed overtime. I know for a while we did 98% for HQ. And for a while we may have calculated the accuracy using the whole sequence length (not excluding the trimmed region) which would've made the accuracy 99% instead of 98%.

--Liz

**Comment by nlhepler** [comment]
I can confirm what @Magdoll says is true: you get these 0-PHRED QVs (and lowercase bases) when Arrow or Quiver fail (to converge, or because of insufficient input coverage, etc). I can't say more about what happened with your example without looking at an INFO debugging log from the variantCaller or equivalent script that Iso-Seq ran to perform the final polishing.

**Comment by sjin09** [comment]
Cheers for the detailed answers! They have been immensely helpful! I will close the issue now.
